language: node_js
sudo: false
node_js:
  - "7"
install:
  - npm install uglify-es -g
script:
  - uglifyjs $TRAVIS_BUILD_DIR/src/mapFactory.js --compress --output $TRAVIS_BUILD_DIR/release/mapFactory.min.js  
deploy:
  provider: releases
  api_key: 
    secure: "hAOxG3DzjW+gSH9tBs72UGy+aAsY5Xpb7YUEZPRbC+EveDkuVuNM0C4+8W0jIvJ6Gj2YXt0xWDECq/E8gS68V64uRZG0RsZzz2D7hfX2s+VegU9EGYsKLIQUUNTOl8R+0SuIHZUkNbKlvRqi7JiDDO3UQKaL/a+aJsNpacKUN7JGIEeIEYkvLADkGRnIrCGmWet4ENAA6/FGdMqRV64DomtVCFN6NDPdHAkMOjzlKf5uPeSUdVt1/dU0BPhgH6vYevPc1FzE5PZOMPNDSVpqBGt9PRpEsxS/sGWPq5qVyWP/KMQTzDyOpVS/J8Vywl5i9wGbq6OyXiIm4FyoP6J9kfIYMtppGK6D/FQtv7eZtVlSA1GSD65uH9FKLcYWTKVQtxW5s8KomZXdHoP55IxEqjC6NYc7sDOuw00DtQOGu2jGtZDYy74SWBQITf9IQMP3PF2kfgU01n+dYr0bFoatuVIBODNVdO197giPI8vFedksgYA3URrm3ozzP7FWB1weY24Nme1nvIHgOiUR+GgddoOHOoQR48L/57qfYw/QLxHssRNa+25fPrZMFjunkdgE7CAk0qyk/Xk8k9w+R9wJ/MXVFArZKCRMvLojv/c3f+crXm9a4r1hS+inku399/HN+UaRBiJ1bsD/Z5GQwRMrt2hk8DUKmP6AgyTITa/wPVk="
  file: $TRAVIS_BUILD_DIR/release/mapFactory.min.js
  skip_cleanup: true
